version: '3.8'

services:
  app:
    build: .
    container_name: graduation-be-server
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/graduation
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - graduation-network

  mariadb:
    image: mariadb:latest
    container_name:   mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: graduation
      MARIADB_USER: root
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - graduation-network

volumes:
  mariadb_data:

networks:
  graduation-network:
