services:
  app:
    build: .
    container_name: graduation-be-server
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - graduation-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - graduation-network

volumes:
  mariadb_data:

networks:
  graduation-network:
